apiVersion: v1
kind: ServiceAccount
metadata:
  name: bellor-api
  namespace: bellor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bellor-api-role
  namespace: bellor
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bellor-api-binding
  namespace: bellor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bellor-api-role
subjects:
  - kind: ServiceAccount
    name: bellor-api
    namespace: bellor
